checks/icmp.go
cmd/run.go
cmd/serve.go
fixtures/http_multiple.yaml
fixtures/http_pass.yaml
fixtures/icmp_fail.yaml
fixtures/icmp_pass.yaml
go.mod
go.sum
pkg/api.go
pkg/metrics.go

Regarding https://github.com/flanksource/canary-checker/issues/15

ICMP Check #15

---

checks/s3_bucket.go
fixtures/http_multiple.yaml
fixtures/http_pass.yaml
fixtures/s3_bucket_fail.yaml
fixtures/s3_bucket_pass.yaml
go.mod
go.sum
pkg/api.go
test/e2e.sh
test/e2e_test.go
test/run_test.go

E2E tests for s3 using minio

---

checks/namespace.go
checks/pod.go
checks/utils.go
cmd/run.go
cmd/serve.go
fixtures/namespace_pass.yaml
fixtures/pod_fail.yaml
fixtures/pod_pass.yaml
pkg/api.go

Fixes #46 
Fixes #47 
Fixes #48

Namespace check + pod reuse name + use every node of the cluster

---

checks/pod.go
fixtures/pod_fail.yaml

Improve logging when pod fails to start due to ErrImagePull, ContainerConfigError

---

api/v1/checks.go
checks/dns.go
cmd/serve.go
fixtures/dns_fail.yaml
fixtures/dns_fail_timeout.yaml
fixtures/dns_pass.yaml

add dns timeout

---

config/manager.yaml

feat: all liveness/readiness probes

---

Makefile
release.sh
statuspage/package-lock.json

feat: Add windows support

---

fixtures-crd/mssql_fail.yaml
fixtures-crd/mssql_pass.yaml
fixtures/mssql_fail.yaml
fixtures/mssql_pass.yaml
test/config.yaml
test/e2e.sh
test/setup.yml

feat: add e2e tests for mssql

---

README.md

Should I give a full explanation of the data structures of JSONCheck, Authentication* and kommons.EnvVar Objects, or have I explained how they are called well enough?

docs: Update HTTP check documentation

---

go.mod
go.sum
pkg/aggregate/aggregate.go

feat: /api/aggregate should use a cache

---

README.md
api/v1/checks.go
checks/http.go
config/crd.yaml
go.mod
go.sum
pkg/metrics/metrics.go

feat: add NTLM HTTP support

---

Makefile

chore: fix kustomization update

---

.github/workflows/lint.yml
Makefile
config/deploy/base.yaml
config/deploy/manifests.yaml

chore: fail CI incase of change in auto-generated files

---

cmd/operator.go
pkg/controllers/canary_controller.go

fix: allow filtering by multiple namespaces

---

.github/workflows/release.yml
fixtures/datasources/_setup.yaml
fixtures/datasources/kustomization.yaml
fixtures/git/git_test_expression_pass.yaml
fixtures/git/kustomization.yaml
fixtures/kustomization.yaml

Needs https://github.com/flanksource/aws-sandbox/pull/5 to be merged for full testing

chore: add dispatch call to trigger aws-sandbox action

---

go.mod
go.sum
pkg/api.go
pkg/controllers/canary_jobs.go
pkg/db/canary.go

fix: improve safety around db deletion

---

pkg/topology/query.go

feat: add incidents in topology query

---

.github/workflows/release.yml

@moshloop please do have a look and give feedback thanks!

Update incident commander

---

pkg/system_api.go
pkg/topology/query.go

feat: support for config insights and summary in topology query

---

pkg/db/init.go

fix: change path for embedded postgres

---

pkg/api.go
pkg/db/canary.go
pkg/jobs/canary/canary_jobs.go
pkg/topology/checks/component_check.go

Fixes: https://github.com/flanksource/canary-checker/issues/826

fix: handle invalid canary spec and update job history

---

api/v1/constants.go
cmd/root.go
pkg/db/check_statuses.go
pkg/jobs/jobs.go

Fixes: https://github.com/flanksource/canary-checker/issues/839

feat: delete old check statuses

---

pkg/topology/run.go

fix: panic on empty check results 

---

cmd/serve.go
pkg/api/run_now.go
pkg/db/canary.go
pkg/db/topology.go
pkg/jobs/system/system_jobs.go
pkg/topology/run.go
pkg/utils/utils.go

Resolves: https://github.com/flanksource/canary-checker/issues/934

feat: add run now handler for checks & system template

---

checks/alertmanager.go
checks/common.go
fixtures/datasources/alertmanager.yaml
go.mod
go.sum
hack/generate-schemas/go.mod
hack/generate-schemas/go.sum
pkg/api.go
pkg/cache/postgres.go
pkg/db/canary.go
pkg/jobs/canary/canary_jobs.go
pkg/utils/utils.go

Depends on https://github.com/flanksource/duty/pull/111

feat: create checks from transformed check results

---

pkg/db/canary.go
pkg/jobs/canary/canary_jobs.go

fix: handle invalid canary parsing

---

pkg/topology/run.go

fix: do not sync components for deleted topologies

---

templating/js/k8s.js

chore: add log selectors to pods

---

.github/workflows/release.yml

@moshloop Self merging as release pipeline is broken

fix: add minimal and full images to release pipeline

---

fixtures/datasources/alertmanager_fail.yaml
fixtures/datasources/prometheus.yaml

- Post commit tests failing
- change `canary.lab.flanksource.com` to `demo.aws.flanksource.com`

fix: modify cluster endpoint

---

.golangci.yml
api/v1/canary_types.go
pkg/api.go
pkg/controllers/canary_controller.go
pkg/metrics/metrics.go

Fixes: https://github.com/flanksource/canary-checker/issues/1034

fix: status update for controllers and use canary id from k8s crd

---

chart/templates/serviceaccount.yaml
chart/values.yaml

Required for adding GCP SA annotations

feat: allow annotations to be configured on service account

---

pkg/db/canary.go

Fixes: https://github.com/flanksource/canary-checker/issues/1093

fix: mark transformed checks as deleted

---

fixtures/datasources/alertmanager_fail.yaml

fix: alertmanager forever transitioning

---

api/v1/constants.go
cmd/serve.go
pkg/db/canary.go
pkg/jobs/canary/prometheus_cleanup.go
pkg/jobs/jobs.go
pkg/metrics/metrics.go

Resolves: https://github.com/flanksource/canary-checker/issues/1073

feat: new job to clean up prometheus gauges of deleted checks.

---

pkg/db/init.go

Fixes: https://github.com/flanksource/canary-checker/issues/1102

feat: do not run changelog trigger migration

---

go.mod
go.sum
pkg/controllers/suite_test.go
pkg/jobs/canary/canary_jobs.go
pkg/jobs/canary/canary_jobs_test.go
pkg/jobs/canary/suite_test.go

Resolves: https://github.com/flanksource/canary-checker/issues/1004

feat: prevent concurrent execution of the same canary job

---

api/v1/component_types.go
api/v1/zz_generated.deepcopy.go
checks/runchecks.go
config/deploy/crd.yaml
config/deploy/manifests.yaml
config/schemas/component.schema.json
config/schemas/topology.schema.json
pkg/system_api.go

Resolves: https://github.com/flanksource/canary-checker/issues/947

add labels to component spec

---

templating/js/k8s.js

Fixes: https://github.com/flanksource/flanksource-ui/issues/1286

fix: set property.max as null if it is 0

---

pkg/topology/checks/component_check_test.go
pkg/topology/checks/suite_test.go

Fixes: https://github.com/flanksource/canary-checker/issues/1119

feat: add test for component check relationships

---

api/v1/checks.go
checks/kubernetes.go
go.mod
go.sum
templating/js/k8s.js

feat: add status for pods

---

checks/alertmanager.go

Fixes: https://mission-control.azure.lab.flanksource.com/incidents/018921fc-07b9-9bc8-3530-ada20249d3a7

chore: update alertmanager check name generating algo

---

.golangci.yml
api/context/context.go
canary-checker.properties
checks/ec2.go
checks/runchecks.go
cmd/run.go
cmd/serve.go
go.mod
pkg/api/run_now.go
pkg/jobs/canary/canary_jobs.go
pkg/topology/run.go
pkg/utils/properties.go
test/run_test.go

Resolves: https://github.com/flanksource/canary-checker/issues/1146

feat: disabled checks

---

api/v1/checks.go
api/v1/zz_generated.deepcopy.go
checks/alertmanager.go
config/deploy/crd.yaml
config/deploy/manifests.yaml
config/schemas/canary.schema.json
config/schemas/component.schema.json
config/schemas/health_alertmanager.schema.json
config/schemas/topology.schema.json
fixtures/datasources/alertmanager_fail.yaml

Fixes: https://github.com/flanksource/canary-checker/issues/1097

feat: add option to exclude alerts via labels

---

pkg/db/canary.go

Fixes: https://github.com/flanksource/canary-checker/issues/1211

fix: only update labels and spec for canaries on conflict

---

pkg/jobs/canary/canary_jobs.go
pkg/jobs/jobs.go

Resolves: https://github.com/flanksource/canary-checker/issues/1237

chore: do not record canary sync successes to job history

---

api/v1/checks.go
checks/pod.go
config/deploy/crd.yaml
config/deploy/manifests.yaml
config/schemas/canary.schema.json
config/schemas/component.schema.json
config/schemas/health_pod.schema.json
config/schemas/topology.schema.json

https://github.com/flanksource/canary-checker/issues/1232

[bug] Canary-check: Pod: Issue with scheduling pods in case taints and tolerations using #1232

---

pkg/api.go
pkg/cache/postgres.go

Resolves: https://github.com/flanksource/canary-checker/issues/1255

fix: canaries created from UI were not being saved

---

.github/workflows/postgres-and-push-test.yml
cmd/operator.go
pkg/jobs/canary/canary_jobs.go
test/e2e-postgres-push.sh

Resolves: https://github.com/flanksource/canary-checker/issues/1252

fix: blocking of canary checks on serve mode

---

build/full/Dockerfile
checks/common.go

fix: label handling for transformed checks

---

pkg/db/topology.go

fix: gorm query for deleting topologies

---

pkg/jobs/canary/sync_upstream.go
pkg/jobs/jobs.go

resolves: https://github.com/flanksource/canary-checker/issues/1433

fix: reuse upstream client on canary pull job

---

checks/http.go

resolves: https://github.com/flanksource/canary-checker/issues/1481

feat: enable url templating

---

config/deploy/crd.yaml
config/deploy/manifests.yaml
config/schemas/canary.schema.json
config/schemas/component.schema.json
config/schemas/health_folder.schema.json
config/schemas/health_s3.schema.json
config/schemas/topology.schema.json
go.mod
go.sum
hack/generate-schemas/go.mod
hack/generate-schemas/go.sum
pkg/db/init.go

Enable changelog triggers to push checks to upstream

feat: add changelog triggers

---

api/v1/checks.go
checks/kubernetes.go
config/deploy/crd.yaml
config/deploy/manifests.yaml
config/schemas/canary.schema.json
config/schemas/component.schema.json
config/schemas/health_kubernetes.schema.json
config/schemas/topology.schema.json
fixtures/k8s/kubernetes_pass.yaml

chore: fix conflicting namespace selector

---

pkg/jobs/topology/topology_jobs.go

Fixes: https://github.com/flanksource/canary-checker/issues/1553

fix: topology reloading on updated spec

---

Makefile

fix: do not compress darwin binaries

---

pkg/controllers/system_controller.go
pkg/db/topology.go

fix: topology crd delete gorm query

---

go.mod
go.sum
hack/generate-schemas/go.mod
hack/generate-schemas/go.sum
pkg/system_api.go
pkg/topology/component_relationship_test.go

Depends on: https://github.com/flanksource/duty/pull/430
Closes: https://github.com/flanksource/mission-control/issues/752

refactor: component selector logic

---

pkg/topology/component_relationship.go

@moshloop We were not cleaning up old relationships if no new ones were created

fix: delete old component relationships if no new relationships are created

---

pkg/topology/component_config.go
pkg/topology/component_relationship.go

Fixes: https://github.com/flanksource/canary-checker/issues/1601

chore: cleanup ghost component and config relationships

---

chart/templates/deployment.yaml
chart/values.yaml

```
Error: unknown flag: --check-status-retention-period
Usage:
canary-checker operator [flags]
```

fix: app crashing due to deprecated flags

---

pkg/topology/cleanup.go

```
2024/02/01 05:30:55 logger.go:165: /app/pkg/topology/cleanup.go:67 ERROR: interval out of range (SQLSTATE 22008)
[1.951ms] [rows:0] 
DELETE FROM canaries
WHERE
id NOT IN (SELECT canary_id FROM checks) AND
(NOW() - deleted_at) > INTERVAL '1 day' * 604800000000000
```

fix: check cleanup range interval

---

pkg/jobs/canary/canary_jobs.go
pkg/jobs/jobs.go
pkg/jobs/topology/topology_jobs.go

Changes logic for transformation checks, review that carefully
Lots of invalid check status errors

chore: add check cleanup and refactor transform logic

---

go.mod
go.sum
hack/generate-schemas/go.mod
hack/generate-schemas/go.sum
pkg/db/check_statuses.go

resolves: https://github.com/flanksource/canary-checker/issues/1666

fix: check statuses cleanup job

---

api/v1/canary_types.go
pkg/api/run_now.go
pkg/db/canary.go
pkg/echo/server.go
pkg/jobs/canary/canary_jobs.go
pkg/jobs/canary/relationships.go
pkg/jobs/canary/status.go

resolves: https://github.com/flanksource/canary-checker/issues/1665

feat: run check endpoint

---

pkg/topology/cleanup.go

considers components that are linked to playbooks

fix: CleanupSoftDeletedComponents job

---

checks/sql.go

The sql checks attempts to scan columns of all types as a string.
This PR adds better supports for scanning columns to appropriate native Go types.
This is helpful in the templates as you don't have to cast anything.

fix: sql check scanner

---

pkg/topology/run.go

Fixes: https://github.com/flanksource/canary-checker/issues/1716

chore: do not delete old components in case of failed lookup

---

api/context/context.go
api/v1/checks.go
api/v1/zz_generated.deepcopy.go
checks/kubernetes.go
checks/sql.go
config/deploy/crd.yaml
config/deploy/manifests.yaml
config/schemas/canary.schema.json
config/schemas/component.schema.json
config/schemas/health_kubernetes.schema.json
config/schemas/topology.schema.json
pkg/kube.go

resolves: https://github.com/flanksource/canary-checker/issues/1715

feat: support custom kube config for kubernetes check

---

.github/workflows/release.yml

Fixes: https://github.com/flanksource/canary-checker/issues/1602

feat: auto prerelease

---

chart/templates/clusterrole.yaml
chart/templates/clusterrolebinding.yaml
chart/values.yaml

resolves: https://github.com/flanksource/canary-checker/issues/1507

feat: add rbac to helm values

---

config/deploy/crd.yaml
config/deploy/manifests.yaml
config/schemas/component.schema.json
config/schemas/health_catalog.schema.json
config/schemas/topology.schema.json
go.mod
go.sum
hack/generate-schemas/go.mod
hack/generate-schemas/go.sum
pkg/jobs/topology/topology_jobs.go
pkg/topology/component_config_test.go
pkg/topology/run_test.go

configure topology job run now from properties

---

go.mod
go.sum
hack/generate-schemas/go.mod
hack/generate-schemas/go.sum
pkg/db/check_statuses.go
pkg/jobs/canary/canary_jobs.go
pkg/jobs/canary/sync.go
pkg/jobs/canary/sync_upstream.go
pkg/jobs/topology/topology_jobs.go
pkg/topology/cleanup.go
pkg/topology/component_check.go
pkg/topology/component_config.go
pkg/topology/component_relationship.go

resolves: https://github.com/flanksource/canary-checker/issues/1770

fix: topology job history cleanup

---

fixtures/k8s/cronjob_monitor_fail.yaml
fixtures/k8s/kustomization.yaml

resolves: https://github.com/flanksource/canary-checker/issues/1753

feat: add a canary fixture to monitor cronjob

---

fixtures/k8s/kubernetes_resource_ingress_pass.yaml
fixtures/k8s/kubernetes_resource_namespace_pass.yaml
fixtures/k8s/kustomization.yaml

ref: https://github.com/flanksource/docs/pull/201#discussion_r1584437055

feat: add new fixture for namespace creation

---

pkg/telemetry/tracer.go

resolves: https://github.com/flanksource/mission-control-chart/issues/173

add tenant id to traces

---

pkg/jobs/canary/sync.go

chore: ignore success history for canary jobs

---

api/v1/system_types.go
config/deploy/crd.yaml
config/deploy/manifests.yaml
config/schemas/topology.schema.json
fixtures/topology/kubernetes-cluster-group-by.yaml
pkg/db/canary.go
pkg/topology/run.go
pkg/topology/run_test.go

resolves: https://github.com/flanksource/mission-control-registry/issues/162

feat: support grouping topologies by tags

---

.github/workflows/release.yml

chore: add ecr release flow

---

pkg/topology/run.go

resolves: https://github.com/flanksource/canary-checker/issues/1924

feat: support selectors in groupby

---

.github/workflows/release.yml
Makefile
build/full/Dockerfile
build/minimal/Dockerfile

resolves: https://github.com/flanksource/canary-checker/issues/1938

feat: build docker image for arm64

---

pkg/jobs/canary/sync.go

resolves: https://github.com/flanksource/canary-checker/issues/2018

fix: triggerAt panic

---

fixtures/external/github-webhook.yaml

resolves: https://github.com/flanksource/canary-checker/issues/2012

fix: update github webhook check

---

pkg/system_api.go

resolves: https://github.com/flanksource/canary-checker/issues/1817

feat: config_id on components

---

.golangci.yml
checks/jmeter.go
checks/kubernetes_resource.go
checks/tcp.go
fixtures/external/crossplane-kubernetes-resource.yaml
pkg/db/canary.go

Fixes: https://github.com/flanksource/canary-checker/issues/2052

chore: add crossplane s3 bucket check

---

chart/values.schema.json
chart/values.yaml

Workload deployments failing due to this

fix: incorrect schema property for global.labels

---

pkg/topology/component_relationship.go

In https://github.com/flanksource/duty/pull/1084, we would have to inject component ID manually due to the context

chore: template resource selector search

---

README.md

MR fixes some broken links in the main README

CHG: fix readme links

---

pkg/topology/component_config.go

Fixes: https://github.com/flanksource/config-db/issues/1050

chore: optimize config_component relationship sync job

---

pkg/jobs/canary/canary_jobs.go

there are two jobs named `CleanupChecks`

chore: rename duplicate job

---

pkg/jobs/canary/canary_jobs.go

```
ERR [CleanupCRDDeletedCanaries] failed to schedule job: failed to parse duration @every 1d: time: unknown unit "d" in duration "1d"
```

fix: job schedule for CleanupCRDDeletedCanaries

---

api/v1/checks.go
chart/templates/deployment.yaml
chart/values.schema.json
chart/values.yaml
cmd/root.go
pkg/metrics/metrics.go

resolves: https://github.com/flanksource/canary-checker/issues/2227

feat: use check label in metrics

---

pkg/db/topology.go

Fixes: https://github.com/flanksource/canary-checker/issues/2270

chore: fail topology run if any child component persistence fails

---

api/v1/common.go
config/deploy/crd.yaml
config/deploy/manifests.yaml

resolves: https://cloud-native.slack.com/archives/C05FAKP937V/p1729610687120029

fix: canary CRD. kubebuilder annotation on metrics

---

cmd/root.go
go.mod
pkg/api.go
pkg/metrics/metrics.go
pkg/results.go

related: https://github.com/flanksource/canary-checker/issues/2221

feat: check db error

---

api/v1/checks.go
checks/kubernetes_resource.go

resolves: https://github.com/flanksource/canary-checker/issues/2335

feat: set canary as the controller owner of all created resources

---

checks/kubernetes_resource.go

resolves: https://github.com/flanksource/canary-checker/issues/2340

fix(kubernetes resource): retry on resource not found

---

api/v1/component_types.go
config/deploy/Canary.yml
config/deploy/Component.yml
config/deploy/Topology.yml
config/deploy/manifests.yaml
config/schemas/canary.schema.json
config/schemas/component.schema.json
config/schemas/health_exec.schema.json
config/schemas/topology.schema.json
go.mod
go.sum
pkg/system_api.go

Add hidden property

---

checks/database_backup_gcp.go
fixtures/git/git_test_expression_pass.yaml

resolves: https://github.com/flanksource/canary-checker/issues/2456

fix (cloudsql backup): handle empty connection

---

pkg/controllers/canary_controller.go

resolves: https://github.com/flanksource/canary-checker/issues/2468

fix: reset messages in crd status

---

checks/mysql.go
checks/sql.go
fixtures/datasources/mysql_pass.yaml
go.mod
go.sum

resolves: https://github.com/flanksource/canary-checker/issues/2561
dependsOn: https://github.com/flanksource/duty/pull/1416

fix: mysql check (remove the mysql:// prefix)

---

Makefile
api/v1/checks.go
api/v1/zz_generated.deepcopy.go
config/deploy/Canary.yml
config/deploy/manifests.yaml
config/schemas/canary.schema.json
config/schemas/component.schema.json
config/schemas/health_tcp.schema.json
config/schemas/topology.schema.json
fixtures/minimal/tcp.yaml

resolves: https://github.com/flanksource/canary-checker/issues/2610

feat: tcp display
