flanksource/canary-checker

checks/http.go, fixtures/http_fail.yaml
appending result in DNS fail cases and move to next entry. Test case added in http_fail.yaml file.
=> append result in DNS fail case and move to next entry

statuspage/src/components/BarPopover.vue, statuspage/vue.config.js
closes https://github.com/flanksource/canary-checker/issues/96
The answer was a lot less "industrial" than I initially imagined:
as long as _the show delay_ >= _the hide delay_ the page won't display two popovers at the same time.
The previous settings of waiting 50ms to show a popover when hovering and waiting 350ms to hide it after moving off it was a recipe for multiple displayed at the same time.
=> Prevent multiple overlapping popovers for graph

.github/workflows/binary.yml, .github/workflows/docs.yml, .github/workflows/test.yml, .gitignore, Makefile, cmd/serve.go, fixtures/postgres_succeed.yaml, go.mod, statuspage/static.go, test/config.yaml, test/e2e.sh
Fixes #128 
Fixes #125 
Updated build chain to go1.16 based images
Included static content using go embed instead of esc
removed 'pack' make target
Updated karina version used in testing
=> Switch from ESC to go embed

api/v1/canary_types.go, config/crd.yaml, pkg/aggregate/aggregate.go, pkg/api.go, pkg/cache/cache.go, pkg/metrics/metrics.go, statuspage/package-lock.json, statuspage/src/App.vue, statuspage/src/components/CanaryModal.vue, statuspage/src/components/CanaryStandardServerRow.vue, statuspage/src/components/TableRow.vue, statuspage/src/store/index.js
closes #136
Added a pop-up for the canary. When someone clicks on any canary a popup will open with the canary details
The popup looks like:
=> feat: Add popup on a canary with its details

.gitignore, test/config.yaml, test/e2e.sh
There are still some that have logic specific to the CI environment that fail. For example the restic ones require a absolute path to the ca certificate, which hard-codes the path from the CI
=> feat: support running most e2e tests locally

checks/ec2.go
differentiate between post-test and stale terminations in ec2 logs
=> feat: improve ec2 log output

api/v1/canary_types.go, checks/common.go, checks/junit_xml.go, checks/runchecks.go, cmd/serve.go, config/deploy/crd.yaml, config/deploy/manifests.yaml, fixtures/minimal/http_pass_results_mode_pass.yaml, pkg/cache/cache.go, pkg/controllers/canary_controller.go
Tested the below with the following canary:
```yaml
apiVersion: canaries.flanksource.com/v1
kind: Canary
metadata:
name: http-pass
spec:
resultMode: "junit"
interval: 30
http:
- endpoint: https://httpstat.us/200
thresholdMillis: 3000
responseCodes: [201, 301, 200]
responseContent: ""
maxSSLExpiry: 7
description: "HTTP dummy test 2"
- endpoint: https://httpstat.us/201
thresholdMillis: 3000
responseCodes: [201]
responseContent: ""
maxSSLExpiry: 7
description: "second http check here"
```
On the UI looks like:
On the API endpoint:
On the details endpoint:
=> feat: add junit results mode

chart/templates/servicemonitor.yaml, go.mod, go.sum
The servicemonitor selector needs to use the labels set on the service, not in the service's selector
=> fix: set servicemonitor selector labels to match service labels

pkg/topology/query.go
=> fix: change field names in topology query and hide configs by default

README.md, chart/Chart.yaml, chart/templates/_helpers.tpl, chart/templates/postgres-secret.yaml, chart/values.yaml
@moshloop I have not updated the flanksource-ui.backend field yet.  We discussed jsut hardcoding the service name, so that the samevalue can be in the values file as default.  Everywhere else, things are named after the release name set as at runtime, so it  will be a big discrepancy if just that one has a hardcoded name.
=> Install instructions

README.md, chart/templates/postgres-secret.yaml
Realised I correctly catered for the case where secret values were specified apriori, but didn't add in the extra logic to keep the password static if not.
=> fix: postgres secret creation logic

.github/workflows/release.yml
This trigger was always failing, on closer inspection noticed that we don't use that workflow anymore, so removing the trigger and also the receiver: https://github.com/flanksource/aws-sandbox/pull/95
=> chore: remove old trigger workflow push to sandbox

go.mod, go.sum, pkg/system_api.go
Update go.mod after https://github.com/flanksource/duty/pull/26 is merged
=> chore: use relationship id when constructing topology tree

pkg/jobs/canary/canary_jobs.go
Fixes: https://github.com/flanksource/canary-checker/issues/837
=> chore: add minimum runtime between canary jobs

chart/templates/deployment.yaml
Fixes: #945 
The root shouldn't have the `data/` subdirectory included
=> fix: use new embedded db path in chart

pkg/topology/run.go
Fixes: https://github.com/flanksource/canary-checker/issues/1014
=> fix: component namespace should take precedence over topology namespace

fixtures/datasources/kustomization.yaml
`alertmanager.yaml` to `alertmanager_fail.yaml`
=> bug: fixing typo in Kustomization

build/full/Dockerfile, checks/alertmanager.go
Fixes: https://github.com/flanksource/canary-checker/issues/1013
Names will now look like this:
```
+-------------------------------------------------------------+
| name                                                        |
|-------------------------------------------------------------|
| alertmanager-check                                          |
| KubePodCrashLooping-dev/backend-admin-app-6c4f67756c-sld95  |
| KubeStateMetricsListErrors                                  |
| KubePodNotReady-default/k8s-check-not-ready                 |
| KubeJobFailed-demo/create-postgres-db                       |
| Watchdog                                                    |
| KubeletTooManyPods-ip-10-0-6-69.eu-west-2.compute.internal  |
| KubePodCrashLooping-prod/public-website-777dbd4c57-96wdl …
```
=> feat: add name suffix for alertmanager check

checks/pod.go, fixtures/k8s/pod_pass.yaml
Fixes: https://github.com/flanksource/canary-checker/issues/1028
=> fix: handle empty ingress config for pod check 

checks/dns.go
Fixes: https://github.com/flanksource/canary-checker/issues/1054
=> fix: sort copy of dns results

test/e2e-postgres-push.sh
Fixes: https://github.com/flanksource/canary-checker/issues/1064
=> fix: wait for server to be ready in postgres-push-test

fixtures/k8s/pod_fail.yaml
=> chore: update pod_fail fixture to fail on serving traffic

pkg/db/canary.go
```
2023-06-23T10:13:39.522Z	ERROR	error persisting check with canary 018843b8-45ab-d66a-0c6c-ad6e4995a767: ERROR: there is no unique or exclusion constraint matching the ON CONFLICT specification (SQLSTATE 42P10)
```
=> fix: add agent_id to check unique clause

checks/azure_devops_test.go, checks/common.go, checks/runchecks.go, pkg/jobs/canary/canary_jobs.go, pkg/utils/utils.go
=> fix: cron flow for canaries

pkg/cache/postgres_query.go
Fixes: https://github.com/flanksource/canary-checker/issues/1115
Fixes: https://mission-control.azure.lab.flanksource.com/incidents/0188e7df-4a98-d640-6bac-729b991c02ab
=> fix: merge canary and check labels for summary api

pkg/db/canary.go, pkg/jobs/canary/canary_jobs.go
Fixes: https://mission-control.azure.lab.flanksource.com/incidents/018929f8-be24-2368-7983-a4e47955d5b5
=> chore: delete transformed checks from cron

pkg/cache/postgres_query.go
Resolves: https://github.com/flanksource/canary-checker/issues/1154
=> fix: graph API returns check statuses in chronological order when windowing

build/full/Dockerfile, build/minimal/Dockerfile, cmd/offline.go, pkg/jobs/canary/canary_jobs.go
=> fix: download embedded postgres binary in docker image

pkg/api.go, pkg/controllers/canary_controller.go, pkg/jobs/canary/canary_jobs.go, pkg/topology/checks/component_check.go
Fixes: https://github.com/flanksource/duty/issues/229
@moshloop @adityathebe 
Removed some dead logic and redundant conditions which I don't think was necessary. Please do a double check on this
=> fix: add canary_id to job_history and cleanup sync canary function

go.mod, go.sum, hack/generate-schemas/go.mod, hack/generate-schemas/go.sum, pkg/jobs/canary/suite_test.go, pkg/topology/checks/suite_test.go, pkg/topology/suite_test.go
Update go.mod after https://github.com/flanksource/duty/pull/235 is merged
=> refactor: move common test logic to separate package

cmd/operator.go, pkg/db/canary.go, pkg/jobs/canary/canary_jobs.go
Resolves: https://github.com/flanksource/canary-checker/issues/1282
=> feat: only run sync jobs for canaries of specified namespaces

api/context/context.go, api/context/functions.go, checks/common.go, checks/metrics.go, checks/runchecks.go, checks/sql.go, fixtures/datasources/posgres_stateful_pass.yaml, fixtures/opensearch/_setup.yaml, go.mod, go.sum
This new function lets you use the result of a previous check to template a sql query - this enables building reliable counters from sql tables
=> Stateful checks

fixtures/external/alertmanager.yaml, pkg/jobs/canary/canary_jobs.go
resolves: https://github.com/flanksource/canary-checker/issues/1417
=> feat: persist webhook checks even if there's no schedule

cmd/root.go, pkg/api/suite_test.go, pkg/api/webhook_test.go, pkg/db/canary.go, pkg/jobs/canary/canary_jobs.go, pkg/jobs/canary/canary_jobs_test.go
resolves: https://github.com/flanksource/canary-checker/issues/1423
=> fix: ignore webhook checks when using delete transformation strategy

pkg/jobs/jobs.go
@moshloop FYI this also missing leading to those database topology jobs not getting scheduled
=> chore: add sync topology job to scheduler

fixtures/k8s/kustomization.yaml
```
canaries   148d   False   kustomize build failed: accumulating resources: accumulation err='accumulating resources from 'k8s': read /tmp/kustomization-2520510114/fixtures/k8s: is a directory': recursed accumulation of path '/tmp/kustomization-2520510114/fixtures/k8s': accumulating resources: accumulation err='accumulating resources from 'namespace_pass.yaml': open /tmp/kustomization-2520510114/fixtures/k8s/namespace_pass.yaml: no such file or directory': must build at directory: not a valid directory: evalsymlink failure on '/tmp/kustomization-2520510114/fixtures/k8s/namespace_pass.yaml' : lstat /tmp/kustomization-2520510114/fixtures/k8s/namespace_pass.yaml: no such file or directory
```
=> chore: fix k8s kustomization

install-service.ps1
2 Main Fixes
1. Fixed windows powershell script by doing the following
1.1 Removed deprecated options
1.2 Added Postgres local storage location creation
1.3 Added skip DB migrations option to prevent crash
1.4 Added parameter to install, uninstall & reinstall to make these operations easier
1.5 Added ability to use local canary-checker executable if one exists, prevent needless download & allow for installing custom build
2. Fixed Postgres not shutdown, this is due to log.fatal after Postgres started. Fix is to simply explicitly call shutdown before these statements.
=> fix: windows service script & postgres shutdown

chart/templates/postgres-secret.yaml
Fixes: https://github.com/flanksource/canary-checker/issues/1766
=> fix: sslmode for default database setup

.github/workflows/helm-test.yml
Fixes: https://github.com/flanksource/canary-checker/issues/1773
=> feat: helm chart setup and test

chart/templates/_helpers.tpl, chart/templates/postgres-service.yaml, chart/templates/postgres-statefulset.yaml
Fixes: https://github.com/flanksource/canary-checker/issues/1765
=> chore: fix labels for postgres in helm chart

api/v1/checks.go, checks/kubernetes_resource.go, config/deploy/crd.yaml, config/deploy/manifests.yaml, config/schemas/canary.schema.json, config/schemas/component.schema.json, config/schemas/topology.schema.json, fixtures/k8s/kubernetes_resource_ingress_pass.yaml, fixtures/k8s/kubernetes_resource_pod_exit_code_pass.yaml, fixtures/k8s/kubernetes_resource_service_pass.yaml
resolves: https://github.com/flanksource/canary-checker/issues/1782
=> fix: better deletion of resources

checks/kubernetes_resource.go, fixtures/k8s/kubernetes_resource_pod_exit_code_pass.yaml, pkg/kube.go
* fix: when fetching multiple resources concurrently, we were writing to a slice from multiple goroutines resulting in a race condition. Changed it to use a channel.
* fix: changed `ClientByKind` to `ClientByGroupVersionKind`
* Removed unused method `WaitForResource`
* use templating in the fixture
=> fix(kubernetes check): race condition

checks/kubernetes.go, checks/kubernetes_resource.go, pkg/db/canary.go
resolves: https://github.com/flanksource/canary-checker/issues/1829
removed context pointers in those two checks.
tested locally.
=> feat: context leaking in kubernets & kubernetes resource check

chart/templates/deployment.yaml
So it can use the global value when being used as a subchart
=> fix: otel labels in helm chart

.github/workflows/release.yml
```
Before
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        73G   53G   21G  72% /
tmpfs           7.9G  172K  7.9G   1% /dev/shm
tmpfs           3.2G  1.1M  3.2G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/sdb15      105M  6.1M   99M   6% /boot/efi
/dev/sda1        74G  4.1G   66G   6% /mnt
tmpfs           1.6G   12K  1.6G   1% /run/user/1001
After
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        73G   43G   31G  59% /
tmpfs           7.9G  172K  7.9G   1% /dev/shm
tmpfs           3.2G  1.1M  3.2G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/sdb15      105M  6.1M   99M   6% /boot/efi
/dev/sda1        74G  4.1G   66G   6% /mnt
tmpfs           1.6G   12K  1.6G   1% /run/user/1001
```
=> chore: clear disk space for docker images

api/v1/checks.go, canary-checker.properties, checks/kubernetes_resource.go, fixtures/k8s/kubernetes_resource_pod_exit_code_pass.yaml
resolves: https://github.com/flanksource/canary-checker/issues/2086
---
On the display template of a **kubernetes resource check**, a new `display: map[string]string` variable is made available. The `display` variable contains the display output of all of the checks defined within the kubernetes resource check.
A default display expression is also added for **kubernetes resource check** _(which I think should probably be added to all the checks)_.
```
display.keys().map(k, k + ': ' + display[k]).join(' | ')
```
This expression simply concats `<check name>: <display> | <check name>: <display> ...`
Example: here's the display of 3 checks
=> feat: add display for kubernetes resource check

cmd/operator.go
```
panic: assignment to entry in nil map
goroutine 1 [running]:
github.com/flanksource/canary-checker/cmd.run(0xc013e86200?, {0x6efbe09?, 0x4?, 0x6efbe0d?})
/app/cmd/operator.go:106 +0x765
github.com/spf13/cobra.(*Command).execute(0xa9b0400, {0xc000a03030, 0x7, 0x7})
/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0xa9afe40)
```
=> fix: nil map entry when watch namespace is enabled

cmd/push.go, pkg/api.go, pkg/cache/postgres.go
resolves: https://github.com/flanksource/canary-checker/issues/2059
=> feat: limit check status duration to maxInt32 milliseconds.

pkg/controllers/canary_controller.go, pkg/utils/utils.go, pkg/utils/utils_test.go
resolves: https://github.com/flanksource/canary-checker/issues/2060
=> fix: attempt multiple time formats when parsing triggerAt

pkg/controllers/canary_controller.go, pkg/db/canary.go, pkg/jobs/canary/canary_jobs.go, pkg/jobs/canary/sync.go, pkg/runner/runner.go, pkg/utils/utils.go
resolves: https://github.com/flanksource/canary-checker/issues/2199
=> fix: canary suspension

pkg/topology/component_relationship.go
```
error syncing relationships: ERROR: ON CONFLICT DO UPDATE command cannot affect row a second time (SQLSTATE 21000)
```
=> chore: dedup component relationship rows

cmd/operator.go, cmd/serve.go, pkg/jobs/canary/canary_jobs.go, pkg/jobs/jobs.go, pkg/runner/runner.go
resolves: https://github.com/flanksource/canary-checker/issues/2232
=> feat: add a new job to reconcile forced deleted canaries linked to CRD

checks/alertmanager.go, checks/database_backup.go, checks/elasticsearch.go, checks/namespace.go, checks/utils.go, pkg/results.go
=> chore: remove unused functions

Makefile, config/deploy/crd.yaml, config/deploy/manifests.yaml
```yaml
apiVersion: canaries.flanksource.com/v1
kind: Canary
metadata:
name: domain
spec:
schedule: "@every 1m"
http:
- name: myDomain
url: https://mydomain.com/
thresholdMillis: 20000
responseCodes: [201, 200, 301]
metrics:
- name: canary_checker_custom_http_status
type: gauge
value: "1"
labels:
- name: check_name
valueExpr: check.name
- name: url
valueExpr: check.url
```
Was giving this error (Reported on Slack)
```
Error from server (BadRequest): error when creating "myDomain.yaml": Canary in version "v1" cannot be handled as a Canary: strict decoding error: unknown field "spec.http[0].metrics[0].labels", unknown field "spec.http[0].metrics[0].name", unknown field "spec.http[0].metrics[0].type", unknown field "spec.http[0].metrics[0].value"
```
=> fix: add additional properties in crd for metrics obj

checks/kubernetes_resource.go
Fixes: https://github.com/flanksource/canary-checker/issues/2267
=> fix: ignore URL field when templating kubernetes resource

checks/kubernetes_resource.go
Fixes: https://github.com/flanksource/canary-checker/issues/2268
=> fix(kubernetes-resource): handle default display template error in case of timeout

chart/templates/rbac.yaml, chart/values.schema.json, chart/values.yaml
Fixes: https://github.com/flanksource/canary-checker/issues/2271
@moshloop Should we allow specific args for managing flux resources or argo resources or having an "extra" is fine ?
This is being added for the helm resource tutorial, by default canary checker cannot create flux resources
=> chore: allow arbitary args in chart rbac

README.md
The indents come out slightly off if copied from README as is. This is to fix the formatting.
It's pretty clear in the rich diff of this commit: https://github.com/flanksource/canary-checker/pull/2301/files?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
=> fix: formatting of the quick start canary check in README

chart/README.md, chart/ci/full-values.yaml, chart/templates/rbac.yaml, chart/values.schema.deref.json, chart/values.schema.json, chart/values.yaml
This PR introduces RBAC permissions to allow the Canary Checker to create and delete Kubernetes deployments (see full allowance list below), as required for specific deployment-related tests. These changes support the `deploymentCreateAndDelete` setting in values.yaml.
Allowance list:
- get
- list
- watch
- create
- update
- patch
- delete
Solves https://github.com/flanksource/canary-checker/issues/2308
=> feat: Add RBAC rules for Kubernetes Deployment tests

Makefile, checks/junit.go
This is to fix #2318.
Instead of initializing Volumes / VolumeMounts within the Junit check it only appends to the existing set of volume mounts (which may be empty in probably nearly all cases).
=> Allows volume mounts in JUnit checks

pkg/jobs/jobs.go, pkg/jobs/topology/topology_jobs.go
Fixes: https://github.com/flanksource/duty/issues/1184
=> chore: add reconcile job for deleted crds

api/v1/checks.go, checks/kubernetes_resource.go
resolves: https://github.com/flanksource/canary-checker/issues/2341
=> fix: only set the canary in the ownerReferences if the namespace is known & matches the resources's namespace

cmd/root.go, pkg/metrics/metrics.go
Fixes: https://github.com/flanksource/canary-checker/issues/2350
=> fix: remove time.Sleep from metrics init

pkg/controllers/canary_controller.go, pkg/jobs/canary/status.go
resolves: https://github.com/flanksource/canary-checker/issues/2373
=> feat: set "Invalid" status on canary CRD status

api/v1/checks.go, checks/s3.go, config/deploy/Canary.yml, config/deploy/manifests.yaml, config/schemas/canary.schema.json, config/schemas/component.schema.json, config/schemas/health_s3.schema.json, config/schemas/topology.schema.json
Allow configuring S3 check to use a non-default storage class for PutObject.
The storage class is specified as a raw string to allow for new values in the future as well as non-AWS custom storage classes.
=> feat(s3): allow specifying storage class for PutObject

api/v1/checks.go, checks/sql.go, config/deploy/Canary.yml, config/deploy/manifests.yaml, config/schemas/canary.schema.json, config/schemas/component.schema.json, config/schemas/health_mssql.schema.json, config/schemas/health_mysql.schema.json, config/schemas/health_postgres.schema.json, config/schemas/topology.schema.json
This pull request introduces a new SQL check feature that allows users to define a timeout duration to cancel long-running queries. By default, the timeout is set to 1 minute.
=> feat:(sql) Add Timeout to sql check to cancel queries after timeout
